# Generated by Django 5.2.8 on 2025-12-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology'), ('Electronics', 'Electronics'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enrollment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='semester',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
