# Generated by Django 5.2.8 on 2026-01-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_department_userprofile_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_campus_setup_completed',
            field=models.BooleanField(default=False),
        ),
    ]
