# Generated by Django 5.2.8 on 2025-12-26 06:11

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventregistration',
            old_name='timestamp',
            new_name='registered_at',
        ),
        migrations.RenameField(
            model_name='eventregistration',
            old_name='student',
            new_name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='department',
            field=models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology'), ('Electronics', 'Electronics'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='semester',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='target_role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Faculty', 'Faculty'), ('Student', 'Student'), ('Staff', 'Staff')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'user')},
        ),
    ]
