# Generated by Django 5.2.8 on 2025-12-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_rename_timestamp_notice_created_at_notice_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
