# Generated by Django 5.2.8 on 2025-12-25 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_notice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='status',
        ),
    ]
