# Generated by Django 5.2.8 on 2026-01-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_usernoticestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernoticestatus',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
