# Generated by Django 5.2.8 on 2026-01-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0006_usernoticestatus_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
